# Generated by Django 4.0.3 on 2022-04-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_video_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='GolfClub',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='video',
            name='GolfCourse',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
