# Generated by Django 4.0.3 on 2022-04-07 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0005_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Id', to=settings.AUTH_USER_MODEL),
        ),
    ]
