# Generated by Django 4.0.3 on 2022-03-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_login_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='owner',
        ),
    ]
