# Generated by Django 4.0.3 on 2022-03-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='videofile',
            field=models.FileField(null=True, upload_to='accounts/', verbose_name=''),
        ),
    ]
