# Generated by Django 4.0.3 on 2022-03-29 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_delete_userpicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='videofile',
            new_name='profile_pic',
        ),
    ]
