# Generated by Django 4.0.3 on 2022-06-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApi', '0002_videos_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
