# Generated by Django 4.0.3 on 2022-06-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VideoApi', '0002_videos_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='airtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='angle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='datum',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='golfbaan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='golfclub',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='rpm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='simulatie',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='travel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='xas',
            field=models.IntegerField(null=True),
        ),
    ]
