name: Django CI

on:
  push:
    branches: '*'
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: gts-be
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: gts-be
        DBUSER: root
        DBPASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DBHOST: 127.0.0.1
        DBPORT: ${{ job.services.mysql.ports[3306] }}
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: gts-be
        DBUSER: root
        DBPASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        DBHOST: 127.0.0.1
        DBPORT: ${{ job.services.mysql.ports[3306] }}
